### ISSUE TITLE
Bazel 0.19 Support

### ISSUE THREAD

**Issue by jjudd** [higherkindness/rules_scala#122]
Annex warns on some things in 0.19. I'm working on fixing them, but using this issue to document the things I'm running into

```...depends on deprecated target '@local_jdk//:java': Don't depend on targets in the JDK workspace; use @bazel_tools//tools/jdk:current_java_runtime instead (see https://github.com/bazelbuild/bazel/issues/5594).```

**Comment by jjudd** [comment]
Hah. I'm going to push hard to get the s3 pr merged because upgrading to HEAD every few months is less than ideal :D

**Comment by pauldraper** [comment]
:)

HTTP basic auth with lamda@edge or API gateway authenticator....it could happen.
