### ISSUE TITLE
Move and rename to higherkindness/rules_scala2

### ISSUE THREAD

**Issue by andyscott** [higherkindness/rules_scala#150]
It's time to move this outside of my personal account. I propose we move the repo to https://github.com/higherkindness/ and rename it to rules_scala2, where it can live indefinitely. Current maintainers will remain under the new org. I'd only propose we move it again if we move it to the bazelbuild org.

cc @jjudd @pauldraper current maintainers
cc @raulraja the other admin of the higherkindness org

**Comment by pauldraper** [comment]
Moving to higherkindness is a good change.

I believe bazelbuild is the optimal home for Bazel projects seeking adoption, and that we should request that. Whether before or after, I don't care.

**Comment by jjudd** [comment]
Agree with @pauldraper on this one. Asking the Bazel team about this seems worthwhile. Otherwise, I imagine we will always struggle with adoption.

**Comment by andyscott** [comment]
Rename and move to the higherkindness org is complete. We can slowly refactor the code to remove the annex names as we update code.
