### ISSUE TITLE
Scaladoc rule fails when including dependencies

### ISSUE THREAD

**Issue by kjbass** [higherkindness/rules_scala#178]
When using the `scaladoc` rule and including a `dep` tag I get the following error.  Stacktrace points to https://github.com/higherkindness/rules_scala/blob/cbfb7a14ad8e0c45f8eaa2f7508086c212d50b6f/rules/scala/private/doc.bzl#L27

Not sure if this is something to do with my environment, or a known problem with the scaladoc rule, but wanted to put this out here in case anyone else is running into a similar issue.

If more information is needed, or this is not the proper format you all prefer for issues to be created in please let me know, definitely don't want to be creating superfluous issues if I am just missing something obvious.

```
'JavaInfo' object has no attribute 'transitive_compile_time_deps'
Available attributes: annotation_processing, compilation_info, compile_jars, full_compile_jars, outputs, runtime_output_jars, source_jars, transitive_compile_time_jars, transitive_deps, transitive_exports, transitive_runtime_deps, transitive_runtime_jars, transitive_source_jars
```

**Comment by SrodriguezO** [comment]
Thanks for spotting this @kjbass 

I went ahead and opened a PR with a fix and updated the scaladoc test s.t. it tests using deps. It seems we meant to use JavaInfo's `transitive_deps` attribute. 

Once the fix is merged you should be good to go. Let us know if you run into any other issues :)

**Comment by kjbass** [comment]
That sounds great, thanks for the super quick turnaround time!  If I find anything else I'll be sure to let you all know.
