### ISSUE TITLE
Pass select tags from target to generated actions as execution requirements

### ISSUE THREAD

**Issue by SrodriguezO** [higherkindness/rules_scala#187]
The `tags` attribute lets us tell Bazel to treat certain actions specially; for example, the "no-remote" tag will inform Bazel that an action should not be run remotely even if it otherwise would.

Unfortunately, Bazel doesn't automatically propagate tags from a rule to the actions the rule generates. We need to explicitly do this propagation in our rule implementations.

See: https://github.com/bazelbuild/bazel/issues/7766

**Comment by SrodriguezO** [comment]
I'm happy to take this issue sometime this week.

**Comment by SrodriguezO** [comment]
It appears that this will be taken care of upstream in the future: https://docs.google.com/document/d/1X2GtuuNT6UqYYOK5lJWQEdPjAgsbdB3nFjjmjso-XHo/edit?ts=5ca70ed0#

I'll still open a PR with a fix for `higherkindness/rules_scala` though. This way we'll get expected behavior sooner than later. For future consistency, I'll only propagate the labels specified in the design proposal linked above.

**Comment by ishikhman** [comment]
@SrodriguezO I've just created PR yesterday ;) https://github.com/bazelbuild/bazel/pull/8612

**Comment by SrodriguezO** [comment]
Ah woops, I totally missed that. Thanks @ishikhman! :) 

I'll leave this issue open though; I imagine the fix to `bazelbuid/bazel` will go out in a future release? I'd prefer to not block the fix to `higherkindness/rules_scala` on upgrading Bazel.

**Comment by ishikhman** [comment]
> Ah woops, I totally missed that. Thanks @ishikhman! :)
> 
> I'll leave this issue open though; I imagine the fix to `bazelbuid/bazel` will go out in a future release? I'd prefer to not block the fix to `higherkindness/rules_scala` on upgrading Bazel.

Yes, it will be released somewhere in July.
