### ISSUE TITLE
Thrift / Scrooge Support?

### ISSUE THREAD

**Issue by KaoruDev** [higherkindness/rules_scala#219]
Are there plans to support compiling Thrift to Finagle services via Scrooge?

**Comment by SrodriguezO** [comment]
Not afaik. I'm not sure what this would entail, but if you'd like to provide a design doc we can explore it :) 

However, our team is fully occupied with other work, so if the design is approved, someone outside Lucid would need to implement it (we welcome PRs :))

**Comment by SrodriguezO** [comment]
[bazelbuild/rules_scala](https://github.com/bazelbuild/rules_scala) already supports this, so you could also try using that rule set if that works for your use-case

**Comment by KaoruDev** [comment]
yeah, I currently am using bazelbuild/rules_scala but was interested in leverage `zinc` to decrease compile times. Alas, I couldn't get the two rule sets to work together, may have to revisit if compile times become a problem.

**Comment by SrodriguezO** [comment]
Supporting optional zinc compilation is in the roadmap for `bazelbuild/rules_scala`. I'm not sure how far out it is, but hopefully over the next couple months. Let us know if compile times become an issue before then; would be useful data

**Comment by SrodriguezO** [comment]
Do you mind if I close this issue for now?

**Comment by KaoruDev** [comment]
ah so is the understanding then that this ruleset won't be supported moving forward? 

Could you do you me a favor and share a link to that roadmap? I couldn't find any evidence other than this 2018 issue: https://github.com/bazelbuild/rules_scala/issues/328 which ended with I believe this repo existing in first place =) I'd be excited to see a unified scala rule set!

**Comment by SrodriguezO** [comment]
It was an offline discussion with the maintainers of `bazelbuild/rules_scala`. The goal is to re-unify the rules so people don't have to decide between one set or the other and to decrease duplicate work.

There is no road map document yet, but I can link it here once it's live.

I'm not 100% sure what'll happen `higherkindness/rules_scala` once the rules are unified, but we'll most likely provide a migration path and encourage users to make the switch. We'll probably taper off support during that time. This is all still a few months out though. For the time being, we're still using this rule set internally.

**Comment by KaoruDev** [comment]
dope, I'm looking forward to it!
