### ISSUE TITLE
Passing arguments to test frameworks?

### ISSUE THREAD

**Issue by jakemcc** [higherkindness/rules_scala#222]
I'm trying to run my scalatest tests and exclude tests marked as Slow from running. I'd usually do this by passing `-l org.scalatest.tags.Slow' as arguments to the scalatest.

Is there a way to do this? I've tried a few things that seemed promising but have haven't figured it out yet.

Some of the [documentation](https://github.com/higherkindness/rules_scala/blob/master/docs/newdocs/diff_rules_scala.md) makes me think it _should_ be doable (`Supports <...> custom test framework arguments`) and that I must be missing something.

Any pointers?

**Comment by jakemcc** [comment]
I've kept digging and it seems like passing arguments is not implemented. Here is what I think is the [relevant line](https://github.com/higherkindness/rules_scala/blob/9d6eaa6befa43b7703118cdb6f6acc273192aa0c/src/main/scala/higherkindness/rules_scala/common/sbt-testing/Test.scala#L32)

**Comment by SrodriguezO** [comment]
In https://github.com/higherkindness/rules_scala/blob/master/docs/scala.md#tests there's a note saying this isn't implemented yet. It seems like it should be a fairly straightforward PR. We would love your contribution : )

**Comment by jakemcc** [comment]
Great, because I've started looking at it 😄 !

Before I get going too far in a direction, any thoughts on an approach?

It seems like I'll need to figure out how to get arguments to that bit of code (I've already tested locally that if I just hardcode some arguments for that first argument, it does what I want). That at least seems like it should be fairly straightforward but I'm always happy to receive advice.

**Comment by SrodriguezO** [comment]
I suggest looking at how `TestHelper.withRunner` is called and then trying to pipe the additional options through to it somehow.

I believe you'll ultimately need to add an  `--options` or `--additional_options` argument to `TestRunner` (in `TestRunner.scala`) and then pipe these to `TestHelper.withRunner`

**Comment by jakemcc** [comment]
This was completed with the merge of #226.
