### ISSUE TITLE
User defined JVM arguments on the command line

### ISSUE THREAD

**Issue by susliko** [higherkindness/rules_scala#225]
Is it possible to provide custom VM startup options of the  `scala_binary` targets while running `bazel run` from the command line?
`--jvmopt` (https://docs.bazel.build/versions/master/command-line-reference.html#flag--jvmopt)
seems not to be working in the following run:
`bazel run --jvmopt="-Dfoo=bar" //:app `

**Comment by JaredNeil** [comment]
That `--jvmopt` flag is for passing options to the bazel server on startup.

If you want to pass arguments to your process, you put them after a `--`.

The `scala_binary` rule uses [this wrapper script](https://raw.githubusercontent.com/bazelbuild/bazel/0.27.0/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt) to launch `.jar`s. It takes a `--jvm_flag` option that will forward to the java command.

So this is what you want:
```
bazel run //:app -- --jvm_flag="-Dfoo=bar"
```

**Comment by susliko** [comment]
It worked. Thank you!
