### ISSUE TITLE
Bazel 1.0.0 support

### ISSUE THREAD

**Issue by susliko** [higherkindness/rules_scala#233]
Recently Bazel 1.0.0 was released
https://blog.bazel.build/2019/10/10/bazel-1.0.html

An attempt to build existing code with newest Bazel version fails with an error:
```
File ".../external/rules_scala_annex/rules/scala_proto/private/core.bzl", line 15, 
  in scala_proto_library_implementation
  fail(("disallowed non proto deps in %...))
disallowed non proto deps in [<target //:foo_scala_proto>]
```
while my BUILD file does not contain any non-proto deps:
```
proto_library(
    name = "foo_proto",
    srcs = ["src/main/resources/foo.proto"],
)

scala_proto_library(
    name = "foo_scala_proto",
    deps = [":foo_proto"],
)
```
And it used to build properly with Bazel 0.29.1

**Comment by borkaehw** [comment]
Sorry for getting back to you late. We are aware of this and the pull request was merged recently. https://github.com/higherkindness/rules_scala/pull/236

It should now support Bazel 1.0.0 and 1.1.0. Let us know if you have more questions :smile:

**Comment by susliko** [comment]
It worked indeed! Thank you for delivering newest Bazel versions support :)
