### ISSUE TITLE
NoSuchFileException when running scalafmt

### ISSUE THREAD

**Issue by joprice** [higherkindness/rules_scala#252]
I cannot seem to get a scalafmt test to fail. I either get a no-op success even with poorly formatted sources, or I get a `java.nio.file.NoSuchFileException` for files generated by https://github.com/lucidsoftware/rules_play_routes. Using the glob `srcs = glob(["**/*.scala"], exclude = ["bazel-bin/**/*"]),` helps with the latter, but excluding all bazel directories should be recommended:  `srcs = glob(["**/*.scala"], exclude = ["bazel-*/**/*"]),`. Otherwise, just scanning those directories takes more than 15 seconds. The definition I'm using is

```starlark
load("@rules_scala_annex//rules:scalafmt.bzl", "scala_format_test")
scala_format_test(
    name = "format",
    srcs = glob(["**/*.scala"], exclude = ["bazel-*/**/*"]),
)
```

**Comment by borkaehw** [comment]
You may first refer to how we run `scala_format_test` in this [BUILD](https://github.com/higherkindness/rules_scala/blob/master/tests/format/scalafmt/BUILD), as well as the test [WORKSPACE](https://github.com/higherkindness/rules_scala/blob/master/tests/WORKSPACE) to see if you missed something.

Just a reminder, to test the format, we use `bazel test ...`, to fix the format, we use `bazel run ...`. `bazel build ...` would look like a no-op success.

If you still can't figure it out, please provide a minimal reproducible case. We are happy to take a look.

**Comment by joprice** [comment]
Thanks I'll try that later today

**Comment by joprice** [comment]
Ok I think I was misunderstanding how to use this rule. I was trying to define it once in the repo at the top-level, and then glob all sources, but most sources were actually part of a subpackage. Instead, I assume it is intended to be defined alongside each package that has scala source.
