### ISSUE TITLE
Comparison/Document relationship with bazelbuild/rules_scala

### ISSUE THREAD

**Issue by jatcwang** [higherkindness/rules_scala#261]
For someone new who's dabbling with bazel having two rules_scala is quite confusing, especially when it's not immediately clear why there's two.

I dug around a bit and it seems like it initially started as a playground for some new ideas and aims to eventually fold everything back to bazelbuild/rules_scala
https://gitter.im/bazelbuild_rules_scala/Lobby?at=5ad59ba8109bb04332cde9d3

Is this still the case? Thanks!

**Comment by borkaehw** [comment]
Sorry for late response, I was on a long vacation. It's a long story why we have two `rules_scala`s and why it's still in this way. We currently have active maintainers here so don't worry. We are happy if you can try out higherkindness/rules_scala.

We are still working on figuring out what's the best for both side of communities. I will say the current status/relationship with bazelbuild/rules_scala is good. We have started to bring some good ideas to bazelbuild/rules_scala, and we will continue to do so in the near future.

We used to have document of comparison, but it got outdated easily and is hard to state a clear difference. We also avoid to look rivalrous by listing pros and cons.

**Comment by jatcwang** [comment]
What people like me would like to know is whether this is a temporary playground or an actual alternative implementation. Knowing that this is an actively maintained alternative is good enough for me, thanks :)

**Comment by pauldraper** [comment]
The old comparison document: https://github.com/higherkindness/rules_scala/blob/d601e60da20e475136d96257bb192a9c3130e42d/docs/newdocs/diff_rules_scala.md

Was removed in #232.
