### ISSUE TITLE
Compiling Scala 2.13

### ISSUE THREAD

**Issue by susliko** [higherkindness/rules_scala#275]
For now the rules use `Zinc 1.3.4` version, which requires `Scala 2.12` in the classpath. I am trying to build a `Scala 2.13` code with it in a following manner, as described in the [doc](https://github.com/higherkindness/rules_scala/blob/master/docs/newdocs/scala_versions.md#specifying-the-scala-version-to-use):
```python
compiler_classpath_2_12_10 = [
    "@annex//:org_scala_lang_scala_compiler",
    "@annex//:org_scala_lang_scala_library",
    "@annex//:org_scala_lang_scala_reflect",
]

runtime_classpath_2_13_0 = [
    "@scala_library_2_13_0", // defined in my WORKSPACE
]

configure_bootstrap_scala(
    name = "bootstrap_2_13_0",
    compiler_classpath = compiler_classpath_2_12_10,
    runtime_classpath = runtime_classpath_2_13_0,
    version = "2.13.0",
)

scala_library(
    name = "compiler_bridge_2_13_0",
    srcs = [
        "@compiler_bridge_2_13//:src",
    ],
    scala = ":bootstrap_2_13_0",
    deps = compiler_classpath_2_12_10 + [
        "@annex//:org_scala_sbt_compiler_interface",
        "@annex//:org_scala_sbt_util_interface",
    ],
)

configure_zinc_scala(
    name = "zinc_compiler",
    compiler_bridge = ":compiler_bridge_2_13_0",
    compiler_classpath = compiler_classpath_2_12_10,
    runtime_classpath = runtime_classpath_2_13_0,
    version = "2.13.0",
)

```

And I get an error about wrong Scala signature:
```
error: error while loading package, class file 'bazel-out/k8-fastbuild/bin/external/scala_library_2_13_0/_ijar/scala_library_2_13_0/external/scala_library_2_13_0/scala-library-2.13.0-ijar.jar(scala/collection/package.class)' is broken
(class java.lang.RuntimeException/error reading Scala signature of package.class: Scala signature package has wrong version
 expected: 5.0
 found: 5.2 in package.class)
```
What am I doing wrong? 
Any help would be very apprecieated

**Comment by borkaehw** [comment]
Are you sure `compiler_classpath` 2.12.10 and `runtime_classpath` 2.13.0 are compatible?

**Comment by susliko** [comment]
By the way, the feature-list in the README state the point `Multiple Scala versions in one build, including Scala 3 (Dotty).`. But I didn't manage to find an example of building Scala 3. Is there one? :)

**Comment by borkaehw** [comment]
Sorry for the late response. I have not seen this before and we (as maintainers) are not using 2.13 yet.  Is it a blocker for you?

**Comment by joprice** [comment]
I tried doing the same, but using zinc 1.4.0-M2 with scala 2.13.1 (`org.scala-sbt:zinc_2.13:1.4.0-M2`, `org.scala-sbt:util-interface:1.3.3`, `org.scala-sbt:compiler-interface:1.4.0-M2`)

The bridge compiles and the worker starts, but then I hit the following error: 

`java.lang.NoSuchMethodException: xsbt.CompilerInterface.newCompiler([Ljava.lang.String;, xsbti.compile.Output, xsbti.Logger, xsbti.Reporter)`

**Comment by susliko** [comment]
It seems that we have found a workaround. Replacing manually-compiled `compiler-bridge` with a jar from maven did the trick.
Those settings worked for us:
`WORKSPACE`:
```python
jvm_maven_import_external(
    name = "scala_compiler_bridge_2_13_1",
    artifact = "org.scala-sbt:compiler-bridge_2.13:1.3.4",
    licenses = ["notice"],
    server_urls = ["https://repo1.maven.org/maven2"],
)
```
`BUILD`:
```python
classpath_2_13_1 = [
    "@scala_library_2_13_1//jar",
    "@scala_compiler_2_13_1//jar",
    "@scala_reflect_2_13_1//jar",
]

configure_bootstrap_scala(
    name = "2_13_1",
    compiler_classpath = classpath_2_13_1,
    runtime_classpath = classpath_2_13_1,
    version = "2_13_1",
)

configure_zinc_scala(
    name = "zinc_compiler",
    compiler_bridge = "@scala_compiler_bridge_2_13_1",
    compiler_classpath = classpath_2_13_1,
    global_plugins = [],
    global_scalacopts = [],
    runtime_classpath = classpath_2_13_1,
    version = "2.13.1",
)

```

**Comment by joprice** [comment]
This works for me as well. Thank you!
